# AI-Cursor-Init Configuration
# Copy this file to .cursor-init.yaml in your project root to customize documentation generation

# =============================================================================
# DOCUMENTATION TYPES - Opt-out configuration (all auto-detected by default)
# =============================================================================

# Zero-config behavior: All documentation types are auto-detected and generated
# if they would be useful for your project. Set to 'false' to disable specific types.

documentation:
  # Core documentation (always useful for any project)
  core:
    architecture: true # System architecture overview
    onboarding: true # Developer onboarding guide
    adr: true # Architecture Decision Records

  # Data documentation (auto-detected based on database models)
  data:
    data_model: true # Database schema & ER diagrams (if models found)

# =============================================================================
# TEMPLATE VARIANTS - Choose specific template styles
# =============================================================================

templates:
  # Architecture Decision Records
  adr: "nygard_style" # Options: nygard_style, full, lightweight, madr

  # Architecture documentation
  architecture: "google_style" # Options: google_style, enterprise, arc42

  # Onboarding guides
  onboarding: "developer" # Options: developer, contributor, user

  # Data model documentation
  data_model: "comprehensive" # Options: simple, comprehensive

# =============================================================================
# PROJECT SETTINGS - Project-specific customization
# =============================================================================

project:
  # Project metadata (auto-detected if empty)
  name: "" # Auto-detected from directory name
  description: "" # Auto-detected from package.json/pyproject.toml

  # Generation preferences
  preferences:
    diagram_style: "mermaid" # Diagram format for generated visuals
    documentation_style: "professional" # Writing style preference

# =============================================================================
# GENERATION SETTINGS - Control slash command behavior
# =============================================================================

generation:
  # Content generation options for slash commands
  include_code_examples: true # Include code snippets in documentation
  include_diagrams: true # Generate Mermaid diagrams where applicable
  auto_generate_toc: true # Automatically generate table of contents

# =============================================================================
# EXAMPLES OF COMMON CONFIGURATIONS
# =============================================================================

# Zero-config (default behavior):
# - Analyzes your project automatically using AI
# - Generates useful documentation based on what's detected
# - Perfect for most projects - no configuration needed!

# Minimal documentation only:
# documentation:
#   core: { architecture: true, onboarding: true, adr: true }
#   data: { data_model: false }

# Open source project:
# templates:
#   onboarding: "contributor"  # Contributor-focused onboarding

# Enterprise project:
# templates:
#   architecture: "enterprise"
#   adr: "full"
